News Content Details Component
diegonzs/hermanospc-news pull request #11
Opened 2020-07-10 17:33 UTC by jsiman551

2020-07-10 23:09 UTC, diegonzs requested changes

2020-07-10 23:09 UTC, diegonzs commented on components/news-detail/content/index.js
> +export { NewDetailContent } from './content';
Cambiar NewsDetailContent por Content

2020-07-10 23:28 UTC, jsiman551 commented on components/news-detail/content/index.js
> +export { NewDetailContent } from './content';
Listo! se me había pasado :P

2020-07-11 19:36 UTC, diegonzs approved these changes

2020-07-11 19:37 UTC, merged